# Generated by Django 4.2.24 on 2025-12-11 03:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('files', '0002_alter_fileupload_options_fileupload_batch_id_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('stripe_payment_intent_id', models.CharField(blank=True, help_text='Stripe Payment Intent ID', max_length=255, null=True, unique=True)),
                ('stripe_checkout_session_id', models.CharField(blank=True, help_text='Stripe Checkout Session ID', max_length=255, null=True, unique=True)),
                ('amount', models.IntegerField(help_text='Amount in cents (e.g., 300 = $3.00)')),
                ('currency', models.CharField(default='usd', help_text='Currency code (ISO 4217)', max_length=3)),
                ('payment_tier', models.CharField(choices=[('free', 'Free (≤100MB)'), ('premium', 'Premium (100MB-1GB)'), ('large', 'Large (1GB-5GB)')], default='premium', max_length=20)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('succeeded', 'Succeeded'), ('failed', 'Failed'), ('canceled', 'Canceled'), ('refunded', 'Refunded')], default='pending', max_length=20)),
                ('description', models.TextField(blank=True, help_text='Payment description')),
                ('metadata', models.JSONField(blank=True, default=dict, help_text='Additional payment metadata')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('paid_at', models.DateTimeField(blank=True, null=True)),
                ('refunded_at', models.DateTimeField(blank=True, null=True)),
                ('file_upload', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payments', to='files.fileupload')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='StripeWebhookEvent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('stripe_event_id', models.CharField(help_text='Stripe Event ID', max_length=255, unique=True)),
                ('event_type', models.CharField(help_text='Stripe event type (e.g., payment_intent.succeeded)', max_length=100)),
                ('event_data', models.JSONField(help_text='Complete webhook event data')),
                ('processed', models.BooleanField(default=False, help_text='Whether this event has been processed')),
                ('processed_at', models.DateTimeField(blank=True, null=True)),
                ('error_message', models.TextField(blank=True, help_text='Error message if processing failed')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('payment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='webhook_events', to='payments.payment')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['stripe_event_id'], name='payments_st_stripe__a444ea_idx'), models.Index(fields=['event_type', '-created_at'], name='payments_st_event_t_69488c_idx'), models.Index(fields=['processed', '-created_at'], name='payments_st_process_96dd28_idx')],
            },
        ),
        migrations.AddIndex(
            model_name='payment',
            index=models.Index(fields=['user', '-created_at'], name='payments_pa_user_id_7a85fd_idx'),
        ),
        migrations.AddIndex(
            model_name='payment',
            index=models.Index(fields=['status', '-created_at'], name='payments_pa_status_21ed42_idx'),
        ),
        migrations.AddIndex(
            model_name='payment',
            index=models.Index(fields=['stripe_payment_intent_id'], name='payments_pa_stripe__6fe52c_idx'),
        ),
        migrations.AddIndex(
            model_name='payment',
            index=models.Index(fields=['stripe_checkout_session_id'], name='payments_pa_stripe__6a75d6_idx'),
        ),
    ]
