# Generated by Django 4.2.24 on 2025-09-20 07:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import files.models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FileUpload',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('original_filename', models.CharField(max_length=255)),
                ('file_size', models.BigIntegerField()),
                ('mime_type', models.CharField(max_length=100)),
                ('encrypted_file', models.FileField(blank=True, null=True, upload_to=files.models.upload_to_secure_path)),
                ('download_password', models.CharField(max_length=20)),
                ('download_token', models.UUIDField(default=uuid.uuid4, unique=True)),
                ('status', models.CharField(choices=[('pending', 'Pending Payment'), ('processing', 'Processing'), ('completed', 'Completed'), ('failed', 'Failed'), ('expired', 'Expired')], default='pending', max_length=20)),
                ('pricing_tier', models.CharField(choices=[('free', 'Free (≤100MB)'), ('premium', 'Premium (≤1GB)'), ('large', 'Large (≤5GB)')], max_length=10)),
                ('requires_payment', models.BooleanField(default=False)),
                ('expires_at', models.DateTimeField()),
                ('download_count', models.PositiveIntegerField(default=0)),
                ('last_downloaded', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='uploads', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', '-created_at'], name='files_fileu_user_id_0a4249_idx'), models.Index(fields=['download_token'], name='files_fileu_downloa_37bf1d_idx'), models.Index(fields=['expires_at'], name='files_fileu_expires_714808_idx')],
            },
        ),
    ]
