# Generated by Django 4.2.24 on 2025-12-07 15:49

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('files', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='fileupload',
            options={'ordering': ['-created_at', 'batch_position']},
        ),
        migrations.AddField(
            model_name='fileupload',
            name='batch_id',
            field=models.UUIDField(db_index=True, default=uuid.uuid4),
        ),
        migrations.AddField(
            model_name='fileupload',
            name='batch_position',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='fileupload',
            name='is_batch_upload',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='fileupload',
            name='upload_session_id',
            field=models.CharField(blank=True, db_index=True, max_length=64, null=True),
        ),
        migrations.AddIndex(
            model_name='fileupload',
            index=models.Index(fields=['batch_id'], name='files_fileu_batch_i_edbbea_idx'),
        ),
        migrations.AddIndex(
            model_name='fileupload',
            index=models.Index(fields=['upload_session_id'], name='files_fileu_upload__1a1a05_idx'),
        ),
    ]
